### ISSUE TITLE
Frisco and Mariposa are shifted

### ISSUE THREAD

**Issue by Lexx2k** [BGforgeNet/Fallout2_Unofficial_Patch#100]
Was doing some tests with my alternative worldmap mod and noticed that Frisco and Mariposa are 1px too far to the left .... my turbo autism now prevents me from enjoying the game.

![grafik](https://user-images.githubusercontent.com/4844938/178580536-b0e768af-d9ec-4e86-b662-ac22cc611b64.png)

All other locations in the game are inside the grid, just those two aren't.

**Comment by NovaRain** [comment]
Shifting the `world_pos` of San Fran and Mariposa by 1 should do the trick. In city.txt:
```
[Area 12]                ; Military Base
area_name=Military Base
world_pos=673,1422

[Area 14]                ; San Francisco
area_name=San Francisco
world_pos=473,1322
```
![shifted](https://i.imgur.com/ObK6aT6.png)

**Comment by burner1024** [comment]
> Shifting the `world_pos` of San Fran and Mariposa by 1 should do the trick.

Same for RP enhanced worldmap?

**Comment by NovaRain** [comment]
> > Shifting the `world_pos` of San Fran and Mariposa by 1 should do the trick.
> 
> Same for RP enhanced worldmap?

rpu_enhanced_worldmap.dat only contains replacement FRM files for the world map tiles, it's the records in `city.txt` of both UP/RP need adjustment.

**Comment by burner1024** [comment]
okay, thanks!

**Comment by burner1024** [comment]
Looks like EPA is also shifted
![scr00005_2](https://user-images.githubusercontent.com/1279852/178894248-ed8c68cf-2f6d-4fc5-862b-e4d5e1425b08.jpeg)

**Comment by NovaRain** [comment]
That's the unimplemented EPA in vanilla/UP. In RP EPA is a medium size location so it doesn't matter.

**Comment by burner1024** [comment]
ok, I was hasty
