### ISSUE TITLE
Crash when moving to south NCR

### ISSUE THREAD

**Issue by FelineCinders** [BGforgeNet/Fallout2_Unofficial_Patch#102]
Here a zip with the log and save file!
[https://github.com/FelineCinders/fo2upu/blob/0c4a12287de6068bb54adef00474e306592b7772/crash%20report.zip](url)

**Details:**
Enter south NCR and the game will crash, 100% reproducible 
No other mods installed
Using the PC Gamepass version, English
UPU v26

**Comment by burner1024** [comment]
No crash for me. Try collecting a report with [ZAX](https://github.com/BGforgeNet/zax), it'll grab some extra details.
