### ISSUE TITLE
Dialog mod

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [BGforgeNet/Fallout2_Unofficial_Patch#103]
I'd like to propose dialog mod.

Original Fallout2 hide some answers in dialogs if player doesn't have enough intelligence (IN).
This mod shows when hidden answer is possible, but doesn't disclose its content and doesn't allow to use it.

In other words, it gives player a hint when it makes sense to increase IN (with mentats, perks, etc) and talk to NPC again.

Example:
![scr00000](https://user-images.githubusercontent.com/19704782/209586954-c37d01a8-1142-4d63-b85a-df34a214250c.png)
On this screenshot - answer 5 is hidden. You may unlock it if you get more intelligence, if you select it now - nothing happened, dialog will be ended.

Mod code is here: 
https://github.com/dzmitry-rudnouski/Fallout2_Unofficial_Patch/pull/1/files

**Comment by burner1024** [comment]
I can see how that can be appealing in some cases, however it's not UPU's purpose to provide mods. I recommend that you look into packaging it as a separate mod, preferably with pluggable architecture (not sure if possible, though).
