### ISSUE TITLE
The Dragon's first test did not work properly, the opponent did not initiate combat and after it was over I was stuck in the ring.

### ISSUE THREAD

**Issue by JimAbaddon** [BGforgeNet/Fallout2_Unofficial_Patch#106]
As the title explains, when I started the quest for the Dragon in San Francisco, the first test battle didn't work properly. The opponent didn't initiate combat and I had to do it myself, but after beating him, nothing happened and I remained stuck in the ring. I've seen some mention that this might've been caused because I left the Chinatown map while the scripted fight between the Dragon and Lo Pan was still going but I was under the impression the Unofficial Patch had rectified it. I managed to bypass the issue by losing the first fight, it ended normally and upon retrying it, the entire quest proceeded with no issue but I wanted to report it nonetheless.

I have a save file that I could upload but I'm not sure how to properly do that, for that I apologise.

**Comment by burner1024** [comment]
Zip the save, and attach it in comment.
![Captura desde 2023-01-04 15-11-27](https://user-images.githubusercontent.com/1279852/210511378-1c491118-127b-40c6-a7da-dec24c9974df.png)

**Comment by JimAbaddon** [comment]
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/10342461/SLOT04.zip)

There. I hope it's good enough.

**Comment by burner1024** [comment]
The changelog mentions fixes for Lo Pan himself getting stuck in the ring, not the player.
Do you also have a save before witnessing the scripted fight?

**Comment by JimAbaddon** [comment]
Luckily, I do. I have a separate playthrough saved that I started before restarting and creating my current one, I kept it just in case. It was last saved in NCR before going to San Francisco. I tested it just now and yeah, witnessing the scripted fight end and then starting the tests seemed to make it proceed without issue.
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/10346268/SLOT01.zip)

I attached the save here in case it helps.

**Comment by JimAbaddon** [comment]
Small update: I decided to use that older file to again skip the scripted fight and then do the tests to see if I can recreate the bug but for some reason the test proceeded as normal, at least the first one. I can't say for certain now if skipping the scripted fight triggered it or if it randomly occurred.

**Comment by burner1024** [comment]
The script is convoluted... Hard to understand how it works and why it breaks in your first save.
Can't reproduce the situation either. If you at least find a way to reproduce, please share.

**Comment by JimAbaddon** [comment]
Alright, I'll try to see if I can replicate the situation in a future save file. Thanks.
