### ISSUE TITLE
Endless karma flow with killed Smiley (Klamath).

### ISSUE THREAD

**Issue by Risu** [BGforgeNet/Fallout2_Unofficial_Patch#12]
Minor thing. I am not sure if this is intended, maybe not a bug at all.
I am playing RPU, but this could affect UPU too.
After killing Smiley I can go endlessly through Ardin dialogue and loss 10 karma and gain 5 karma simultaneously:

> Have you found my Smiley yet?
> (Yes I did)
> You found Smiley? Where is he?
> (He's dead. He was eaten by geckos.)
> Eaten by geckos? I just don't believe you...
> (Yeah, you're probably right. Sorry for the scare...)

And karma will change every time through this dialogue.
Savegame from RPU v6:
[SLOT10.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3459138/SLOT10.zip)

**Comment by burner1024** [comment]
Please attach the files [directly to github issues](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/reporting.md).

I can reproduce this on RP 2.3.3, so it must be the same with RPU. What exactly would you change, though?

**Comment by burner1024** [comment]
I guess that's just what you get for torturing an old woman repeatedly.
