### ISSUE TITLE
Something else. I AIN'T DYING FOR THIS! said Ghost to me. (DEN)

### ISSUE THREAD

**Issue by Risu** [BGforgeNet/Fallout2_Unofficial_Patch#13]
Actually it goes alongside fallout 2 humor, but I think it is unintentionally.
I am playing RPUv6, but this should affect UPU too.
I can cripple, knock down and kill ghost through critical shot.
I can plant and steal from ghost for exp points.
During fight crippled ghost crying:
F**k my leg hurts!
I AIN'T DYING FOR THIS!

Screenshots:
![ghost_critical](https://user-images.githubusercontent.com/5950603/62336369-4710ee80-b4d0-11e9-84e9-20b734e990cf.png)
![ghost_killed](https://user-images.githubusercontent.com/5950603/62336379-4d06cf80-b4d0-11e9-8b2f-30c49dc14aae.png)
Savegame (RPUv6):
[SLOT10.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3459226/SLOT10.zip)

**Comment by burner1024** [comment]
ლ(ಠ益ಠლ) Why u gotta kill everything, man?

I think that being able to kill a ghost is absurd enough, and you'll probably see blood spilled, too. Taunts are just cherry on top.
I don't see any meaningful solution to this.

**Comment by Risu** [comment]
So ability to kill and steal from ghost is deliberate by game developers?
Otherwise I can propose fix to the proto.
[00000029.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3462141/00000029.zip)
[Invulnerable + cannot steal from]

**Comment by burner1024** [comment]
I guess that works. Added.
