### ISSUE TITLE
Something else. Cameron does not offer again teaching as promised. (Arroyo)

### ISSUE THREAD

**Issue by Risu** [BGforgeNet/Fallout2_Unofficial_Patch#14]
I am playing RPUv6, but it should affect UPU.
After dialogue with Cameron:
> It is good to see you again...
> (Hello, Cameron. Ready for another fight?)
> You have a tongue of purest silver(...)
> (Ha! Good day to you, Cameron.)
> Chosen One, I could not help but notice that you lack...
> (Thank, but I think I can handle myself just fine.)
> Very well. Return to me if you change your mind.
> (Thanks, Cameron. I will remember your offer).

He doesn't offer teaching anymore.
Savegame before talk (RPUv6):
[SLOT10.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3462671/SLOT10.zip)

**Comment by Risu** [comment]
As fix I propose to add:
`set_local_var(LVAR_Trained,0);`
into procedure Node018 at ACTEMVIL.SSL

**Comment by burner1024** [comment]
I think it's better to set the var after the actual training, rather than flip it back and forth.

**Comment by Risu** [comment]
It's fine, but this way you changing eligibility into always-time-thing (buffout+tag park in later part of the game).
