### ISSUE TITLE
Messed up Czech Translation

### ISSUE THREAD

**Issue by WitmenCz** [BGforgeNet/Fallout2_Unofficial_Patch#145]
I discovered issue when i installed last version of UPU. 

It is **text error on character screen.**

Best solution would be shortened text for Critical strike text line: Instead of (Šance na kritický zásah) to (Kritický zásah).

Unfortunately i can't do code and cant figure out how to edit language files.

![Text Error](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/assets/124618112/a8449e34-edcb-4730-a6ca-cfdff92323ea)

Thank you for your help

WitmenCz

**Comment by burner1024** [comment]
You can translate here https://hive.bgforge.net/projects/fallout/up/cs/.

**Comment by WitmenCz** [comment]
> You can translate here https://hive.bgforge.net/projects/fallout/up/cs/.

Okay. Thank you
