### ISSUE TITLE
A bug of new reno boxing match

### ISSUE THREAD

**Issue by lds888506** [BGforgeNet/Fallout2_Unofficial_Patch#148]
### What happened
In the fourth round of the new reno boxing match, when the fight message "lost your next turn" appears, you will lose the fight directly.
### What you expected to happen
I've tried three times, and encountered the same issue each time. I think it might be a bug.
However, my game recording is in Chinese, I'm not sure if it will affect your judgment.
Game version：steam+upu_v30
### Screenshot

https://github.com/user-attachments/assets/f2444d73-3025-44f6-92e5-66b47d65938f

**Comment by burner1024** [comment]
Why do you think it's a bug? Losing turn counts as knockout.

**Comment by lds888506** [comment]
It was my own attack error that caused the loss of current AP , not losing the current turn.

**Comment by burner1024** [comment]
It doesn't matter what caused turn loss, it's still a knockout.

**Comment by lds888506** [comment]
Alright, I will close this bug then, sorry for the inconvenience.
