### ISSUE TITLE
cassidy leather armor bonus missing from proto (00000089.pro)

### ISSUE THREAD

**Issue by luotettava-asiakas** [BGforgeNet/Fallout2_Unofficial_Patch#16]
so his base AC is 6 with leather armor on but there are no bonuses from leather armor he is wearing.
[00000089.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3487363/00000089.zip)

changed +15 AC bonus and leather armor bonus stats like i think it should be

**Comment by burner1024** [comment]
How can this be seen in game?

**Comment by luotettava-asiakas** [comment]
![cassidy](https://user-images.githubusercontent.com/53438817/62819282-95229380-bb5b-11e9-97a7-8538d17bc3f8.jpg)

**Comment by luotettava-asiakas** [comment]
and here is what i think it should look like and how i edited the file i posted.
![cassidyproto2](https://user-images.githubusercontent.com/53438817/62819354-ce0f3800-bb5c-11e9-8484-cf6f56138a44.jpg)
![cassidyproto1](https://user-images.githubusercontent.com/53438817/62819355-ce0f3800-bb5c-11e9-982b-5a5b92c87b9f.jpg)

**Comment by burner1024** [comment]
I think it shows base AC.

**Comment by luotettava-asiakas** [comment]
In Suliks case I remember it shows base AC + armor bonus. so thats why i thought Cassidy was broken. Cassidy is wearing his armor unlike Sulik.

**Comment by burner1024** [comment]
I need to reproduce this, so can you please [attach a savegame and describe the steps](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/reporting.md)?

**Comment by luotettava-asiakas** [comment]
[SAVEGAME.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3489067/SAVEGAME.zip)

Equip/enequip armor on Sulik and Cassidy.
Sulik should have AC base 7 + 8 from leather jacket
Cassidy has base 6 and no bonus, and when you unequip his armor AC goes 0

**Comment by burner1024** [comment]
You are right. I screwed up with cleaning files in v7. New version should have it right.

**Comment by luotettava-asiakas** [comment]
no it is not your fault.
I believe it is vanilla bug and RP has not fixed it either.
I tested v8 and I think you probably copied the pro file from RP and the issue remains still

**Comment by burner1024** [comment]
Interesting. So all those years Cassidy was a walking target?
But levels accumulate quickly around VC area, that's probably it wasn't noticed.
I added your version now, thanks.
