### ISSUE TITLE
Pip-Boy string length test

### ISSUE THREAD

**Issue by burner1024** [BGforgeNet/Fallout2_Unofficial_Patch#2]
Need to check all strings, max length seems to be ~55 characters.

**Comment by NovaRain** [comment]
Since the Fallout text font is not monospace, maybe check it with all lowercase 'i' and all uppercase 'A' (the widest character)?

**Comment by burner1024** [comment]
I'm not sure what good would that do, there aren't any such strings?

**Comment by NovaRain** [comment]
I'd use that for getting a range of how many chars can fit in a line.

**Comment by burner1024** [comment]
Sorry, I don't get it. Suppose we got a 35-100 range, what next? Probably all lines are already under 100.

**Comment by NovaRain** [comment]
I just tested and it's a stupid idea, sorry.
(about 120 'i' and 39 'A' before clipping with black edge on the right)
I guess it'll require checking all holodisk text in the game.

**Comment by burner1024** [comment]
Maybe just set a reasonable threshold and add a script to point out suspicious lines.
It's not so much of a problem for the original (one time check), but I'm thinking about hooking the [translation system](https://tra.bgforge.net/projects/fallout/up/) directly into this repo, instead of keeping it [separate](https://github.com/BGforgeNet/fallout2-up-translation).

**Comment by burner1024** [comment]
Closing until any good solution is proposed.
