### ISSUE TITLE
define errors

### ISSUE THREAD

**Issue by Lexx2k** [BGforgeNet/Fallout2_Unofficial_Patch#20]
These GVARs are duplicated:

#define GVAR_QUEST_MAGGIE_STILL              (101)
#define GVAR_QUEST_KILL_EVIL_PLANTS          (101)
#define GVAR_DROP_PLAYER_BY_VAULT_8		    (584)
#define GVAR_ENCLAVE_COM_LINE                (584)
#define GVAR_MODOC_LOST_AND_FOUND            (134)
#define GVAR_SALVATORE_FAMILY_COUNTER        (134)
#define GVAR_CORNELIUS_STATE                 (135)
#define GVAR_BISHOP_FAMILY_COUNTER           (135)
#define GVAR_NCR_GENERIC_STATE               (243)
#define GVAR_8_BALL_TOILET_SECRET           (243)

The script has a wrong ID:
#define SCRIPT_BCKARLA          (558)   // BCKarla.int     ; Karla Vault 15 guard
#define SCRIPT_V15SENT          (558)   // V15sent.int     ; vault 15 secret entrance

V15SENT should be 559.

Not sure how much of that is actually used, but I guess it should be fixed anyway.

**Comment by burner1024** [comment]
Right, will check.
