### ISSUE TITLE
Modoc death narration sticks

### ISSUE THREAD

**Issue by jvs3** [BGforgeNet/Fallout2_Unofficial_Patch#21]
After visiting Modoc I have the problem that every time my character dies the special narration from a death during this explosion is played.

"The residents of Modoc eventually found your body a few miles from the outhouse. The stench is so bad they leave your corpse to rot in the waste."

This seems to be linked to this savegame, earlier saves don't have this issue. It is also linked to all deaths, not just the ones from explosions.

Unfortunately the closes save I have is leaving Modoc for the first time. This is after blowing up the outhouse and returning the watch.

[SLOT39.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3658847/SLOT39.zip)

**Comment by burner1024** [comment]
Well, somehow you survived the shitty death. You sure you placed the explosives correctly?
The related scripts weren't changed, though. I would need a pre-explosion save to look into this.

Meanwhile, you can use F12SE and set GVAR_MODOC_SHITTY_DEATH to 0 to stop this from happening in your current game.

**Comment by burner1024** [comment]
Do you use FO2tweaks?

**Comment by jvs3** [comment]
I do use FO2tweaks v10.
[fo2tweaks.ini.txt](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3665859/fo2tweaks.ini.txt)

I also have some savegames.

Entering Modoc:
[SLOT40.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3665852/SLOT40.zip)
Before entering the outhouse:
[SLOT39.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3665851/SLOT39.zip)
In the outhouse:
[SLOT38.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3665850/SLOT38.zip)

I drop the dynamite and the character survives the blast with the message "You made it out of the hole just in time for the explosion to go off behind you, sending you flying through the air."

Every subsequent death has the "The residents of Modoc eventually found your body a few miles from the outhouse. The stench is so bad they leave your corpse to rot in the waste." I tried dying in Modoc, random encounters and Vault City.

Sometimes my character and npcs only take damage and I don't get the message "You made it out of the hole just in time for the explosion to go off behind you, sending you flying through the air." The map also isn't covered in goo in this case. I assume this is vanilla behaviour and I failed a traps check or something and it would be possible to try again.

**Comment by burner1024** [comment]
Do you use the ladder to climb out or map hotkey from FO2tweaks?

**Comment by jvs3** [comment]
I used the ladder

**Comment by burner1024** [comment]
I think I found the problem. Looks like shitty death was never ever in the game - vanilla, UP or RP.
It's enabled in RP sources, but not included in the actual package. But it's never toggled off, thus the situation.

**Comment by burner1024** [comment]
Since it's commented out in original sources, probably the correct way to go about this would be to remove any leftovers from UP, and restore a working version in RP.
