### ISSUE TITLE
black screen after being kicked out by Vortis (NCR)

### ISSUE THREAD

**Issue by jvs3** [BGforgeNet/Fallout2_Unofficial_Patch#23]
In the NCR if I talk to Vortis and pick the first dialog option or ask about work and then refuse my character gets teleported out of the building. My character is then visible for a second outside the building and then the screen goes black with only the fire in the barrel outside visible.

It is still possible to load a game (ctrl + l and then enter) or open the menu (escape) but the black screen stays and I have to alt-tab out of the game to close it.

![Screenshot_20190928_203206](https://user-images.githubusercontent.com/3510562/65820922-33170e00-e22f-11e9-8f60-9865725d60c3.png)

Before entering the NCR for the first time
[SLOT41.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3665873/SLOT41.zip)

Before talking to Vortis
[SLOT42.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3665874/SLOT42.zip)

EDIT: this is with FO2tweaks v10, Restoration Project v8 and sfall v4.1.9.1 and v4.2
I reported it here because I don't think Restoration Project adds anything to Vortis?

**Comment by burner1024** [comment]
RP does add stuff to Vortis, but this applies to both, I made a typo.
Hotfix is attached, extract into data/scripts.
[scvortis.int.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3666471/scvortis.int.zip)
