### ISSUE TITLE
Hakunin crash

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [BGforgeNet/Fallout2_Unofficial_Patch#30]
Crash after attempt to talk to Hakunin:

![hakunin](https://user-images.githubusercontent.com/19704782/69920585-e18f3780-149a-11ea-8c72-076296771a54.png)

Savegame:
[SLOT03.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3908741/SLOT03.zip)

Ddraw 4.2.1.1
[ddraw.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3908750/ddraw.zip)

[debug.log](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3908748/debug.log)

**Comment by burner1024** [comment]
Can reproduce. I assume you were able to talk to him before?

**Comment by dzmitry-rudnouski** [comment]
Sure, I was able to talk to him at game beginning.

**Comment by burner1024** [comment]
Can reproduce on UP 1.02.31 with sfall 4.2.1.1 as well.
Unfortunately, `debug.log` isn't very helpful. Sigh... @FakelsHub, @NovaRain - maybe you have some insight?

**Comment by NovaRain** [comment]
The crash can be reproduced with the save, but if I start a new game I can talk to him normally. I tried loading one of my saves that in later stage of the game and went back to Arroyo, and still able to talk to him.

**Comment by burner1024** [comment]
@dzmitry-rudnouski you haven't used any editors, have you?

**Comment by dzmitry-rudnouski** [comment]
No, but at game start to create character I loaded this manually edited gcd:
[0points.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3910941/0points.zip).
It sets all SPECIAL to 01 to make game as hard as possible.

Also I've got 2 previous saves and can check later if issue is reproducible with them.

**Comment by burner1024** [comment]
@dzmitry-rudnouski please do.

**Comment by FakelsHub** [comment]
Неправильно происходит вход в диалог, ищите ошибку в скрипте.

**Comment by FakelsHub** [comment]
https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/dc8bc07a68fa55cbce47ebd912842ff221e55775/scripts_src/main/ahhakun.ssl#L266
чего-то тут явно  не хвататет. :)

**Comment by burner1024** [comment]
Yeah... @dzmitry-rudnouski extract this into `data/scripts` and try again.
[ahhakun.int.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3912349/ahhakun.int.zip)

@FakelsHub how did you trace it? Is it possible to add some extra logging about this into `debug.log`?

**Comment by dzmitry-rudnouski** [comment]
Now it works, thanks!

**Comment by FakelsHub** [comment]
> how did you trace it?
 Is it possible to add some extra logging about this into debug.log?

В отладчике IDA.
Ну нет.  Каждую ошибку "дурака" будем логировать?))

**Comment by burner1024** [comment]
> В отладчике IDA. Но это можно было бы и в скритпе отследить, во время вызова обработчика..
> Ну нет. Каждую ошибку "дурака" будем логировать?))

Почему все. Только те, которые приводят к крэшу. Но если тебе удобней расчехлять отладчик каждый раз и лично в каждом крэше разбираться, ну ладно.

**Comment by FakelsHub** [comment]
Крашу многое, что приводит если это неправильно использовать.

**Comment by burner1024** [comment]
Я и не предлагаю на все сразу набрасываться. Так, потихоньку, по мере обнаружения известные проблемы добавлять мне кажется было бы полезно. Ну смотри сам.
И да, спасибо за помощь.

**Comment by FakelsHub** [comment]
Краш все равно будет. Ну добавиться сообщение что-то типа: "Не создано окно диалога".  Много оно тебе расскажет почему  и по какой причине оно не создалость?
Я даже без запуска отладчика, певым делом тут в репе посмотрел скрип в частности на пары команд для входа диалог, но из-за отсутствия постветки синтаскиса у гита не увидел сразу нехватку, если открывать скрипт в редакторе с нормальной подсветкой то это сразу обнаруживается.

**Comment by burner1024** [comment]
Я так вообще не знал что что-то там отдельно надо создавать... С диалогами мало работал.

**Comment by FakelsHub** [comment]
start_gdialog() создает окно(интерфейс) диалога и подготовливает пр. дрянь для диалога.

**Comment by burner1024** [comment]
Ну теперь-то знаю.
