### ISSUE TITLE
Pariah Dog crash

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [BGforgeNet/Fallout2_Unofficial_Patch#31]
Crash after attempt to talk to Pariah Dog:

![pariah](https://user-images.githubusercontent.com/19704782/70002862-6305c900-1572-11ea-8c8a-4c361111ab65.png)

Also there is error in messages (bottom left on screenshot) when pointing mouse to dog.

Save:
[SLOT06.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3913720/SLOT06.zip)

Sfall 4.2.1.1:
[sfall.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3913726/sfall.zip)

Logs:
[debug.log](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3913737/debug.log)
[sfall-log.txt](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3913743/sfall-log.txt)

**Comment by burner1024** [comment]
[scripts.lst.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/3914470/scripts.lst.zip)
Try extracting this into `data/scripts`

**Comment by dzmitry-rudnouski** [comment]
Fixed, thank you.

**Comment by burner1024** [comment]
I released a new version containing the fixes for the two bugs you reported.
