### ISSUE TITLE
Knocking Lo Pan unconscious in box ring causes the game stuck there

### ISSUE THREAD

**Issue by ericqzou** [BGforgeNet/Fallout2_Unofficial_Patch#37]
Dear Burner:
I believe I have encountered this bug ever since vanilla many years ago, and then RP, and even now on RPU v0.9, so finally I make this report...

When the dude take the request to challenge Lo Pan and fight him in the ring, Lo Pan can be knocked on the ground unconscious, but not dead.  It seems like the engine then "believes" that the dude wins the fight and ended the combat mode, and the game stuck right there because you can't come out of it, even if you restart a fight (still inside the ring) and kill Lo Pan afterwards.

Just for one hour ago I managed to reproduce this twice with clean installation, and then RPU v0.9. The only extra mod I have installed is Lootable Armor Mod, which I don't think it is related to this problem.

I have zipped one example of savegame while I am stuck inside the ring with Lo Pan. I am sorry that I came to overwrite the savegame slot which is right before I start the challenge itself.

Sincerely yours
Eric
[SLOT09.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/4072125/SLOT09.zip)

**Comment by burner1024** [comment]
OK, first, you'll probably want to upgrade to v10, cause there's a [bug with Shi emperor](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/29).
Second, what's your closest save before starting the fights?

**Comment by ericqzou** [comment]
Yeah I saw the v10 in changelog two days after I started on v9. pity...

I don't have a savegame before the fight any more, i know, it's a shame. But I am certain that the bug i still present even in v10. I planned to play v10 soon. And even I can just start the game in San Fran and make the challenge right away, I will rather prefer to play the game in usual way. I can then reproduce it and remember the savegames this time and report back, if you like so?

**Comment by burner1024** [comment]
About v10, it's not a problem, you can just replace `mods/rpu.dat` with newer version (or apply the linked hotfix).
About the actual bug, I will look into this, that's all I can say for now.

**Comment by ericqzou** [comment]
Thanks. I will leave it to you now.

**Comment by ericqzou** [comment]
Burner:

While I discuss another bug with Novarain, he told me that sfall 4.1.9+ has a fix which will automatically end the combat while no more hostile detected. This may has something to do with this bug. Clearly, this is the situation - within the ring, when Lo Pan is down, no more hostile chars - thus combat ended.

Just a quick thought:)

**Comment by burner1024** [comment]
I loaded your save, entered combat, killed Lo Pan and the game finished the fight correctly, teleporting me out of the ring.

**Comment by ericqzou** [comment]
Hm..... No idea why. Now I loaded it (under V10) and tried it out a couple of times and I get the same result as you. May be it has something to do with the game program is restarted? But I hardly think so.. But well, it's a good thing though..

**Comment by burner1024** [comment]
OK, I'll close this as not reproducible for now, but if you find a way to repeat this, feel free to re-open.
