### ISSUE TITLE
Truncated ddraw.ini

### ISSUE THREAD

**Issue by darlinggj** [BGforgeNet/Fallout2_Unofficial_Patch#38]
Is ddraw.ini supposed to be so much shorter and uncommented than in RPU v9 etc? Many options now seem to be missing; no mention of this in the v10 changelog; I also get the "You have overwitten the RP ddraw.ini etc" message on loading an old save or starting a new game (after having further installed EcCo 0.6.2 + FO2Tweaks 11.2 + sfall 4.2.2 except for its own ddraw.ini).

This is all of it in the v10 download:

[Main]
AllowSoundForFloats = 1
WorldMapSlots = 21

[Misc]
UseFileSystemOverride = 1
FemaleDialogMsgs = 2
NPCAutoLevel = 1
OverrideArtCacheSize = 1
ElevatorsFile = Elevators.ini
DisplayKarmaChanges = 1
PlayIdleAnimOnReload = 1
EnableHeroAppearanceMod = 1
AIDrugUsePerfFix = 1
ExtraSaveSlots = 1
KarmaFRMs = 128,146,129,125,152,127,147,134,176
KarmaPoints = -1000,-750,-500,-249,250,500,750,1000
SpeedInventoryPCRotation = 220
BoxBarColours = 11111
BoostScriptDialogLimit = 1
DontTurnOffSneakIfYouRun = 1
NumbersInDialogue = 1
WorldMapFontPatch = 1
PartyMemberExtraInfo = 1
VersionString = FALLOUT II 1.02d  RP 2.3.3u10

**Comment by burner1024** [comment]
wait, UPU or RPU? And have you launched the script? Windows or Linux?

**Comment by darlinggj** [comment]
Oops--sorry, wrong forum. Yes, RPU. Script launched, wundows 10, moving to the right thread now.
