### ISSUE TITLE
Cult of Personality / Karma beacon

### ISSUE THREAD

**Issue by burner1024** [BGforgeNet/Fallout2_Unofficial_Patch#4]
Need to take a second look at these. As far I understand, if implemented properly, they shouldn't really appear anywhere in the scripts themselves, only in headers. But instead we have

```
scripts_src/NCR/SCMERK.SSL:   if (msgNum == 109 and ( (check_general_rep < KARMA_DEFENDER) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then //edit by killap - added and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)))
scripts_src/NCR/SCMERK.SSL:   if (msgNum == 116 and ( (check_general_rep < KARMA_DEFENDER) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then //edit by killap - added and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)))
scripts_src/RNDENCTR/ECMSTNEW.SSL:   else if ((CITY_START <= 0) and ( (check_general_rep >= 0) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then begin //edit by killap - added (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)))
scripts_src/RNDENCTR/ECCVNMST.SSL:   if ((CITY_START >= 0) and ( (check_general_rep <= 0) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then begin //edit by killap - added not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))
scripts_src/RNDENCTR/ECMSTV15.SSL:   else if ((CITY_START >= 0) and ( (check_general_rep < 0) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then begin //edit by killap - added (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)))
scripts_src/RNDENCTR/ECMSTVC.SSL:   else if ((CITY_START >= 0) and ( (check_general_rep < 0) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then begin //edit by killap - added (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)))
scripts_src/RNDENCTR/ECMSTSAN.SSL:   else if ((CITY_START >= 0) and ( (check_general_rep < 0) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then begin //edit by killap - added (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)))
scripts_src/RNDENCTR/ECMSTDEN.SSL:   else if ((CITY_START <= 0) and ( (check_general_rep >= 0) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then begin //edit by killap - added not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))
scripts_src/RNDENCTR/ECMSTRED.SSL:   else if ((CITY_START >= 0) and ( (check_general_rep < 0) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then begin //edit by killap - added (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)))
scripts_src/RNDENCTR/ECMSTNCR.SSL:   else if ((CITY_START >= 0) and ( (check_general_rep < 0) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then begin //edit by killap - added (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)))
scripts_src/RNDENCTR/ECMSTGEC.SSL:   else if ((CITY_START >= 0) and ( (check_general_rep < 0) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then begin //edit by killap - added not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))
scripts_src/RNDENCTR/ECMSTBRO.SSL:   else if ((CITY_START >= 0) and ( (check_general_rep < 0) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then begin //edit by killap - added not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))
scripts_src/RNDENCTR/ECMSTKLA.SSL:   else if ((CITY_START >= 0) and ( (check_general_rep < 0) and (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))) ) ) then begin //edit by killap added - (not(has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)))
scripts_src/HEADERS/DEFINE.H:#define PERK_cult_of_personality (39)
scripts_src/HEADERS/sfall/define_lite.h:#define PERK_cult_of_personality (39)
scripts_src/HEADERS/MODREACT.H:                                        if (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)) then begin               \
scripts_src/HEADERS/MODREACT.H:                                        if (has_trait(TRAIT_PERK,dude_obj,PERK_cult_of_personality)) then begin                 \
scripts_src/SANFRAN/FCKENLEE.SSL:   if ((neutral_critter_reaction or good_critter_reaction) and ( (check_general_rep >= KARMA_BETRAYER) or (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)) ) ) then //edit by killap - added (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))
scripts_src/NAVARRO/CCXARN.SSL:   if ( (check_general_rep >= 0) or (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)) ) then begin //KARMA not bad --added by killap  (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))
scripts_src/NAVARRO/CCXARN.SSL:   if ( (check_general_rep >= 0) or (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)) ) then begin //KARMA not bad --added by killap -  (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality))
```

**Comment by NovaRain** [comment]
CoP is never fully implemented in UP, even in RP there are still some missing cases.
The karma check conditions are different for each NPC (merchants in random encounters might be more unified). I'm not sure if in headers only really help in this case. Or do you mean something like
`#define check_cult_of_personality has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)`
to make the scripts not too cluttered?

**Comment by burner1024** [comment]
> CoP is never fully implemented (or "fixed") in UP, even in RP there are still some missing cases.

Well, that's in UP scope, right?
Ideally, there'd be just one function calculating NPC reaction - taking into account karma, perks, titles, evil/good critter, etc. That probably won't be possible, but I'm sure the mess could be made less... messy.

I'd start with looking into this:
```
$ grep -R check_general_rep scripts_src/ | wc -l
157
````

**Comment by burner1024** [comment]
OK, so it turns out there __is__ a [function](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/2234d5ec1c7be1c654092c13ed6c366c2d6782e4/scripts_src/headers/modreact.h#L288) calculating reaction. And it even appears to utilize [CoP](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/2234d5ec1c7be1c654092c13ed6c366c2d6782e4/scripts_src/headers/modreact.h#L389) and [KB](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/2234d5ec1c7be1c654092c13ed6c366c2d6782e4/scripts_src/headers/modreact.h#L99) correctly, as far as I understand. "The only" problems with it are:
1. Reaction bonus from karma is [manipulated strangely](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/2234d5ec1c7be1c654092c13ed6c366c2d6782e4/scripts_src/headers/modreact.h#L299), which I don't understand. (Same for [town rep](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/2234d5ec1c7be1c654092c13ed6c366c2d6782e4/scripts_src/headers/modreact.h#L303) bonus).
2. Blatant disregard for reaction levels and using direct karma/title/town rep checks all over the scripts.

---

I think fixing "just" CoP only wouldn't be much of a problem, something like
```c++
procedure effective_karma(variable evil := false) begin
  variable karma := global_var(GVAR_PLAYER_REPUTATION);
  if has_trait(dude_obj, PERK_cult_of_personality) begin
    if evil and karma > 0 then return -1 * karma;
    if not evil and karma < 0 then return -1 * karma;
  end
  return karma;
end
```
More or less the same for "effective_title". Also, as critter being evil may mean that `Evil_Critter==1`, or that `inc_evil_critter` is used, would be good to verify:
1. Whether "Evil_Critter" and "inc_evil_critter" always agree.
2. Whether "inc_neutral_critter" critters have the same reaction to karma as "inc_good_critter".

---

On the broader scope of Karma Beacon, utilizing it properly requires a serious overhaul of the scripts. I do believe that direct checks should be exceptional, and mostly critters should just use reaction (as it includes karma, and even has [grades of sensitivity](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/2234d5ec1c7be1c654092c13ed6c366c2d6782e4/scripts_src/headers/modreact.h#L41) to it). However,
1. It's quite some extra work.
2. In the strict "patch" sense, it could be viewed as "reaching".
3. I'm not actually sure what would be the effect. Will it even be noticeable? Or maybe on the other hand, it'll be overly disruptive in some edge cases?

**Comment by burner1024** [comment]
Here's a diff of who's considered evil by dialog vs who's evil by kill status:

```diff
--- evil_dialog.list	2020-01-22 18:22:26.554222170 +0700
+++ evil_kill.list	2020-01-22 18:22:36.137984863 +0700
@@ -1,4 +1,52 @@
+./base/ecgenmut.ssl
+./base/ecgrunde.ssl
+./base/ecmelchr.ssl
+./base/ectlkmut.ssl
+./brokhill/hcaileen.ssl
+./brokhill/hcfrank.ssl
+./brokhill/hcjacob.ssl
+./brokhill/hcmanson.ssl
+./den/dcflick.ssl
+./den/dcjoey.ssl
+./den/dcmetrom.ssl
+./den/dcmetzge.ssl
+./den/dcpengrd.ssl
+./den/dcrnslvr.ssl
+./den/dcslaver.ssl
+./den/dcslvgrt.ssl
+./den/dcthug.ssl
+./den/dcvicgrd.ssl
 ./enclave/qcfrank.ssl
+./enclave/qcgengrd.ssl
+./enclave/qcgensci.ssl
+./enclave/qcsecbot.ssl
+./generic/zclscorp.ssl
+./klamath/kcdunton.ssl
+./klamath/kcggcust.ssl
+./main/nhmyron.ssl
+./main/qhprzrch.ssl
+./modoc/mcatkdog.ssl
+./navarro/ccacon.ssl
+./navarro/ccatech.ssl
+./navarro/ccchris.ssl
+./navarro/cccomp1.ssl
+./navarro/cccomp2.ssl
+./navarro/ccdoctor.ssl
+./navarro/ccdrgrd.ssl
+./navarro/ccdrill.ssl
+./navarro/ccggbak.ssl
+./navarro/ccgguard.ssl
+./navarro/ccgrdca.ssl
+./navarro/ccgrdpa.ssl
+./navarro/cckevin.ssl
+./navarro/ccmandr.ssl
+./navarro/ccmedgrd.ssl
+./navarro/ccqmstr.ssl
+./navarro/ccquincy.ssl
+./navarro/ccraul.ssl
+./navarro/cctech1.ssl
+./navarro/cctech2.ssl
+./ncr/scbgrd.ssl
 ./ncr/scbuster.ssl
 ./ncr/sclenny.ssl
 ./ncr/scmerk.ssl
@@ -6,16 +54,76 @@
 ./ncr/scmrkgrd.ssl
 ./ncr/scoswald.ssl
 ./ncr/scrawpat.ssl
-./ncr/scskeete.ssl
 ./ncr/scslvgrd.ssl
+./ncr/scslvovr.ssl
 ./ncr/scvortis.ssl
+./newreno/ncangbis.ssl
+./newreno/ncbarten.ssl
+./newreno/ncbigjes.ssl
+./newreno/ncbisgrd.ssl
+./newreno/ncbishop.ssl
 ./newreno/ncbismen.ssl
+./newreno/ncbitch.ssl
+./newreno/nccasbou.ssl
+./newreno/ncchpboy.ssl
+./newreno/nccorbro.ssl
 ./newreno/ncdrgdlr.ssl
+./newreno/nchollyf.ssl
+./newreno/nchsgsal.ssl
+./newreno/nchspow1.ssl
+./newreno/nchspow2.ssl
+./newreno/nchssal1.ssl
+./newreno/nchssal2.ssl
+./newreno/ncjimmyj.ssl
+./newreno/ncjules.ssl
+./newreno/ncliljes.ssl
+./newreno/ncmason.ssl
 ./newreno/ncmormen.ssl
+./newreno/ncmyrgrd.ssl
+./newreno/ncpimp.ssl
+./newreno/ncprosti.ssl
 ./newreno/ncramire.ssl
+./newreno/ncrenesc.ssl
+./newreno/ncresear.ssl
+./newreno/ncrico.ssl
 ./newreno/ncsalmen.ssl
+./newreno/ncsalvat.ssl
+./newreno/ncsheb.ssl
+./newreno/nctray.ssl
+./newreno/nctyson.ssl
+./newreno/nimrbsf.ssl
+./redding/rcfrog.ssl
 ./redding/rchakes.ssl
+./redding/rcmorbrs.ssl
+./redding/rcmotgng.ssl
+./rndenctr/ecbandit.ssl
+./rndenctr/eccanbal.ssl
+./rndenctr/eccanibl.ssl
+./rndenctr/ecclmjmp.ssl
+./rndenctr/eccrazy.ssl
+./rndenctr/ecelvpat.ssl
+./rndenctr/ecgangs.ssl
+./rndenctr/echiwymn.ssl
+./rndenctr/echlyppl.ssl
+./rndenctr/ecmaradr.ssl
+./rndenctr/ecmercs.ssl
+./rndenctr/ecmstamy.ssl
+./rndenctr/ecmstden.ssl
+./rndenctr/ecoutcst.ssl
+./rndenctr/ecpariah.ssl
+./rndenctr/ecprsgng.ssl
+./rndenctr/ecraibow.ssl
+./rndenctr/ecraider.ssl
+./rndenctr/ecrobber.ssl
+./rndenctr/ecrogue.ssl
+./rndenctr/ecscaven.ssl
+./rndenctr/ecslaver.ssl
+./rndenctr/ecspammr.ssl
+./rndenctr/ecwilder.ssl
+./rndenctr/ecyakuza.ssl
+./sanfran/fcbadpea.ssl
 ./sanfran/fcdaveh.ssl
+./sanfran/fcelgrd.ssl
 ./sanfran/fcelrind.ssl
 ./sanfran/fcjuavki.ssl
 ./sanfran/fclopan.ssl
```

At least they don't disagree much, alhtough `inc_evil_critter` list has many more entries. Apparently, most bad guys don't think they are bad. What a surprise.
One discrepancy is Doofus. He's neutral, but prefers evil in conversation. Although it probably doesn't actually matter in his script.

So, I think `Evil_Critter` var should be to determine reaction.

**Comment by burner1024** [comment]
Investigation continues:
1. `REACTION_BONUS_KARMA` was [undefined](https://github.com/NovaRain/Fallout2_Unofficial_Patch/blob/a97eec3f0b3a01532440c28eca21b3d30ed263db/scripts_src/HEADERS/MODREACT.H#L99) in UP 1.02.31, this shouldn't even compile.
2. After [merging](https://github.com/NovaRain/Fallout2_Unofficial_Patch/commit/08247589a689ab03b76ac50c27929eb05e3f21c2#diff-5d48a37cde6603a68e21936347014b40) RP's `modreact.h` it's now `REACTION_BONUS_COMP_KARMA` and it should compile, as well as account for Karma Beacon.
3. The whole -1*(-1) thing is apparently because someone thought that negative values won't get divided properly:
    ```
    if (REACTION_BONUS_COMP_KARMA >= 0) then
      reaction_bonus_karma:=(REACTION_BONUS_COMP_KARMA/KARMA_MODIFIER);
    else
      reaction_bonus_karma:=-1*(-1*REACTION_BONUS_COMP_KARMA/KARMA_MODIFIER);
    ```
    I'm pretty sure it is superfluous, but to be sure, @NovaRain, can you confirm this?

**Comment by burner1024** [comment]
On Karma Beacon: description states
> Your Karma shines twice as bright. Whether good or bad, your Karma is doubled for **any kind** of reaction or modifiers.

However, there are many `check_general_rep` conditions, which don't take it into account. I'm not sure if that falls into the scope... If yes, it would probably be easier to throw away all code related to this perk and simply double karma gains with a global script. That wouldn't be backwards compatible, though, and titles would seemingly be achieved faster.

**Comment by burner1024** [comment]
OK, so `check_general_rep` is used to determine both NPC lines and player responses. My take on this is that NPC lines should use "effective_rep" (taking Cult/Beacon into account), while dude responses should use "real" rep.
For example, `NOption(271 + (check_general_rep < 0), Node999, 004);` stays the same, but `Reply(215 + (check_general_rep >= 0) );` turns into `Reply(215 + (effective_rep >= 0) );`
That way evil PC gets to say evil things, while NPCs get swayed by the Cult (although saying bad things still decreases their reaction).

**Comment by burner1024** [comment]
After all, I think in the long term it's probably best to drop karma/titles/rep/perks checks and go for full, proper [Reaction](https://fallout.fandom.com/wiki/Reaction) implementation instead, in both UP and RP. It's the only way to make all the perks work as they should.

**Comment by burner1024** [comment]
Also need to apply CoP to town rep.

**Comment by burner1024** [comment]
dammit

**Comment by burner1024** [comment]
This should conclude the karma perks saga, I think.
The next big thing would be movig to full Reaction implementation, but that's a tale for another time.
