### ISSUE TITLE
Aldo from Klamath has incorrect coins check for low iq character

### ISSUE THREAD

**Issue by JuanCruzSanFran** [BGforgeNet/Fallout2_Unofficial_Patch#41]
[Buggy line](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/scripts_src/klamath/kcaldo.ssl#L273)

Due to being copy-pasted from Node910, it has incorrect coins check: > 4 instead of > 19

**Comment by burner1024** [comment]
Generally, I prefer to see bugs in-game, to verify they actually exist.
But it does look like a copy-paste error, yes. I'll correct that, or you can submit a pull if you want.

**Comment by JuanCruzSanFran** [comment]
I decided to wait out till you guys run scripts through ReDefine and then edit & pull anything that's left. So yeah, if you don't mind - could you possibly correct it yourself, since I'm fairly new to this whole github workflow?
