### ISSUE TITLE
valtcity/vccurtis.ssl not compiling

### ISSUE THREAD

**Issue by JuanCruzSanFran** [BGforgeNet/Fallout2_Unofficial_Patch#43]
```
vccurtis.ssl:232:1: fatal error: '/*' within block comment [-Wcomment]
/* Set global_variable for Enemy status*/
^
```
Closing multiline comment on [previous line](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/scripts_src/valtcity/vccurtis.ssl#L231):

`   end*-comment out by killap - counts as two childkills then*/`

would fix the error.

**Comment by burner1024** [comment]
I [don't have](https://travis-ci.org/BGforgeNet/Fallout2_Unofficial_Patch) problems with compiling.

**Comment by JuanCruzSanFran** [comment]
I guess my gcc version doesn't want to play nice and preprocess this type of comment. 😕

**Comment by burner1024** [comment]
You may submit a pull removing killap's comment. If you do, please also check/pull RP version for the same, I try to keep them synced.
