### ISSUE TITLE
Undefined symbol OBJ_TYPE_CRITTER in headers/upu.h:24

### ISSUE THREAD

**Issue by JuanCruzSanFran** [BGforgeNet/Fallout2_Unofficial_Patch#45]
I can't find definition for it anywhere in the scripts.

**Comment by burner1024** [comment]
https://github.com/phobos2077/sfall/blob/76b0528e7f0f768d5af8d1e450ed79aa418f1781/artifacts/scripting/headers/define_extra.h#L16
Please keep github issues for reporting bugs. For discussion and other support, there are [forums](https://forums.bgforge.net/viewforum.php?f=34).
