### ISSUE TITLE
Night Vision CtH

### ISSUE THREAD

**Issue by burner1024** [BGforgeNet/Fallout2_Unofficial_Patch#48]
Night Vision changes light level directly, thus affecting all combatants. Ideally, CtH bonus should only apply to the dude. That can be done with a penalty to everyone else, but I'm not sure what's the calculation and whether it'll be too hard to implement.
@novarain do you have the details on CtH formula? I found [this](https://www.nma-fallout.com/threads/what-are-the-chance-to-hit-formulae.202632/#post-4030412), but the link is dead now.

**Comment by NovaRain** [comment]
Here's the pseudocode: http://www.mediafire.com/file/da41rwmj5i7prop/fo2calc_docs.rar/file
And the effects of light level on ToHit chance only applies to the player.

**Comment by burner1024** [comment]
Oh, I see. Thank you.
It is unfair still, the enemies should get penalties. Attacking under cover of darkness sounds like a valid in-game strategy.
But I'm not sure whether that would be in the scope of the patch. I'll be open to input on this, but until someone chimes in, I'm hesitant to make changes. Maybe another component for the tweaks.

**Comment by NovaRain** [comment]
> But I'm not sure whether that would be in the scope of the patch.

I'd say it's completely out of the scope of UP (or even RP). "Player-only" nerf like this is not a bug but a design choice, as much as it might look unfair to some.
