### ISSUE TITLE
Evil Skynet bugged

### ISSUE THREAD

**Issue by giathai** [BGforgeNet/Fallout2_Unofficial_Patch#49]
After killing one of party member (Vic in my case), Skynet still respond with only "give weapon, proceed to surface" and not turn hostile.

I gave it a sarcasm "it's nice to want" to raise the alarm on level 3 (just because). Then I proceed to kill all the bots. get the cybernetic brain. Install that onto the riflebot body.

Now, when we run the sequence to start that up, skynet say skynet will now travel with you. then the next time would be "give weapon, proceed to surface". I can trade with it (thus I give it the ryder BB) and change command (but can not choose best weapon.

Note: when Skynet join on 3rd floor, I already has a 5 member party at CHA7. It force to join in the way Bess, Pariah Dog did, I think.

If, when arrive at the shot-open door we press A to enter combat immediately, so the hostile/kill member script not fired up. Then I run back inside, Skynet would stay on the outside. And when we get out and talk to it, it repeat "give weapon, proceed to surface" but nothing else, no join, no kill, nothing.

Obviously this is intentional, a way to keep evil skynet according to Per guide. But still, it is a broken script~ Can you check?

**Comment by burner1024** [comment]
I think the whole evil Skynet joining is a bug, and killap introduced another bug when made Skynet pop all party members instead of just one.
Save isn't loading, so can't test, but hopefully original behaviour is now restored, and Skynet should remember to keep walking towards the party if they left area.

**Comment by giathai** [comment]
1. evil skynet joining is logical behaviour. It is wanting to leave SAD so it force itself into our party without regard to CHA limit.
2. When moving from ground level back inside the facility, Evil Skynet NOT in party is a bug though it is a minor issue since it has no effect on gameplay.
3. Evil Skynet kill one or all party is an expected behavior from EVIL skynet. But the whole "moving to a party member then kill him/her" is a bug. Too complicated behaviour let to bug, I should think.
If you can make Evil Skynet just "initiate combat, moving to a party member then kill him/her" it would be more snappy than that.
