### ISSUE TITLE
Gigolo

### ISSUE THREAD

**Issue by burner1024** [BGforgeNet/Fallout2_Unofficial_Patch#5]
I really don't like how it's implemented, has nothing to do with description.
I think a much more faithful implementation would be to base the title on the total number of characters engaged, rather the number of times.

Vote this comment thumbs up if you think it's a good idea, or down if it's not.

**Comment by NovaRain** [comment]
I'd say leaving it as it is, at least for UP.

**Comment by burner1024** [comment]
I think I'll just leave it hanging for voting for now.

**Comment by NovaRain** [comment]
> 
> 
> I think I'll just leave it hanging for voting for now.

How about making a thread on NMA? I don't think there are people checking the repo/issues other than you and me.

**Comment by burner1024** [comment]
I think we'll make one with the first postfix release. If there's enough interest, votes will follow and then we'll see.

**Comment by burner1024** [comment]
No one cares, so I'll just leave it as is for now.
