### ISSUE TITLE
Can't pick up plants in Arroyo

### ISSUE THREAD

**Issue by antimeridian** [BGforgeNet/Fallout2_Unofficial_Patch#52]
Started a new game with clean F2 install followed by latest version of UPU (.exe). Character cannot pick up the Broc Flowers and Xander Roots in the hunting grounds. Character begins the kneeling animation for picking up an item but it appears as if the animation gets interrupted. Character stands up partway through and item disappears from ground but does not appear in inventory. Issue does not occur with clean install of the game on my system, only happening with UPU. Savegame attached for what it's worth. Possibly related to recent changes to garden plant respawn behavior?

[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/4760652/SLOT01.zip)

Fallout 2 1.02.31u14 (GOG Classic version)
Sfall 4.2.4 (version included with UPU)

**Comment by burner1024** [comment]
Please try these (drop into `data/scripts`).
[scripts.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/4765071/scripts.zip)
If possible, please also verify respawning logic mentioned in #44 (both plants and geckos).

**Comment by antimeridian** [comment]
Okay, the animation still looks a little funky but the items are now actually moving to my inventory, so that's good. Now I can't actually tell from reading #44 what the practical difference between original and fixed behavior should be - you'll have to forgive me, I'm no programmer. Both plants and geckos are respawning daily but I feel it's more complicated than that. If you tell me what exactly to look for I'd be happy to check.

**Comment by burner1024** [comment]
How about these [scripts.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/4766158/scripts.zip).
The fixed version is supposed to limit how many are spawned. In original, I think each new day there would be more on the same spot, even if you don't pick them up.
Geckos weren't changed, so don't mind that.

**Comment by burner1024** [comment]
It's still messy, though. One option would be to revert it back to the original, after all it worked good enough for anyone to bother. Another it to drop object script shenanigans and just use list_items/critters to get the total count and impose actual limits (spawn when there's less than MIN, but never exceed MAX).
Tagging @NovaRain for reference.

**Comment by antimeridian** [comment]
> How about these [scripts.zip]

This works correctly, all seems to be in order now.

**Comment by NovaRain** [comment]
Got the same results from 1st and 2nd scripts.zip. It seems calling `remove_script(self_obj)` in `pickup_p_proc` works and doesn't causes animation glitch now. Using a check with list_items for total plants on the map in `map_enter_p_proc` from map script might be a less problematic way if that works.

**Comment by burner1024** [comment]
> at least you don't need to care about item stacking with script attached items.
Might still need that, to avoid counting plants that player might've dropped. I realize this is a lot of nitpicking, but UP is about nitpicking, and if we add a fix, I'd like it to be an actual fix, no something half-assed, otherwise what's the point, can just keep the original.
Do you agree with respawning logic that I outlined in the previous message?

**Comment by NovaRain** [comment]
> Do you agree with respawning logic that I outlined in the previous message? (I mean, do you think that's what actually was intended)

TBH I'm not really sure, from original xander/broc scripts source it seems the limit was supposed to be "total xander/broc on the map" since dropping one does try to increase MVAR.

**Comment by burner1024** [comment]
OK, I think I'll just revert to the original then. Maybe revisit this later if there's consensus on how it should actually work.
