### ISSUE TITLE
Crash when doing Lo Pan training

### ISSUE THREAD

**Issue by GDRFunk** [BGforgeNet/Fallout2_Unofficial_Patch#53]
Default sFall. It happens when you end the fight against Wejungh. 
[SLOT02.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/4809825/SLOT02.zip)
![Magus-senpai](https://user-images.githubusercontent.com/64866788/85229808-f50fda80-b3b9-11ea-8780-0cc152f316b0.png)
[debug.log](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/4809826/debug.log)

**Comment by burner1024** [comment]
Training is already completed in the save. I challenge Dragon and kill him successfully.

**Comment by GDRFunk** [comment]
That's strange, I only did Dragon training, and I wanted to complete the Lo Pan training for the XP.

**Comment by burner1024** [comment]
Can you get training from both? I think once you picked one, you stick with it.
Anyway, please provide a save right before talking and challenging the offending fighter.

**Comment by GDRFunk** [comment]
From Per Jorner's guide; "The house with the garden is the Dragon's place. He'll train characters of good alignment (karma 250 or more) for +5% Unarmed each day, a maximum of four times or until you reach 100%. See quests 12 and 13 for more details, but don't challenge any of the martial arts guys to mortal combat until you've taken both their tests for the xp"

**Comment by GDRFunk** [comment]
Also, there's no crash when challenging the fighter, only doing the Lo Pan training line.

**Comment by burner1024** [comment]
So is it line or the actual fight?

This is what Lo Pan says in your save when asked to train.

![Captura de pantalla de 2020-06-22 00-00-47](https://user-images.githubusercontent.com/1279852/85230603-7c416a80-b41b-11ea-98c9-a166b762fd0b.png)

I need a save right before crash and clear instructions to reproduce.

**Comment by GDRFunk** [comment]
![imagen](https://user-images.githubusercontent.com/64866788/85230987-acf4b600-b3c1-11ea-8bd3-718fcf6db487.png)
![imagen](https://user-images.githubusercontent.com/64866788/85231009-cc8bde80-b3c1-11ea-956a-d2e3845feb1c.png)
Who are you? - 1 - 1 - Training

**Comment by GDRFunk** [comment]
[SLOT08.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/4809908/SLOT08.zip)
Training save.

**Comment by burner1024** [comment]
Good, now I can reproduce. See, clarity is important.

Unfortunately thought, I don't see anything out of ordinary in the log, so I guess I'll have to summon the cavalry... @NovaRain, @FakelsHub what could this be? The crash happens when you end players turn. I tried sfall 4.2.5.1, 4.0.8, 3.8.25.1 - no difference.

@GDRFunk please also attach your `fallout2.cfg` and `ddraw.ini` for reference (even if they are default).

Something sound-related?
```
wine: Unhandled page fault on read access to 0C153428 at address 00458646 (thread 0009), starting debugger...
Unhandled exception: page fault on read access to 0x0c153428 in 32-bit code (0x00458646).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:00458646 ESP:0032f988 EBP:02780248 EFLAGS:00010202(  R- --  I   - - - )
 EAX:0000c001 EBX:02780248 ECX:02780248 EDX:0c1533c4
 ESI:00000001 EDI:0c1533c4
Stack dump:
0x0032f988:  9700c001 00000000 029980fb 000003ec
0x0032f998:  ffffffe9 02780248 0046ce70 000004ff
0x0032f9a8:  0032f9e8 7e81d643 00000001 0032fae0
0x0032f9b8:  00000000 000004ff 00000000 00000000
0x0032f9c8:  0000b39a 2f6196ff 7ffd8000 0032f9f0
0x0032f9d8:  0032fa08 7e80d24e 7ffd8000 000004ff
Backtrace:
=>0 0x00458646 EntryPoint+0xffffffff() in fallout2 (0x02780248)
  1 0x02993248 (0x026f0a78)
0x00458646 EntryPoint+0xffffffff in fallout2: movl	0x64(%edi),%eax
Modules:
Module	Address			Debug info	Name (117 modules)
PE	  330000-  3d6000	Deferred        ddraw
PE	  400000-  6f0000	Export          fallout2
PE	  a20000-  c87000	Deferred        d3dx9_31
PE	10000000-10077000	Deferred        f2_res
PE	62340000-623be000	Deferred        uxtheme
PE	62800000-628bc000	Deferred        usp10
PE	639c0000-63b08000	Deferred        winmm
PE	64b40000-64b78000	Deferred        shcore
PE	65200000-6567b000	Deferred        ole32
PE	65980000-6599a000	Deferred        version
PE	66640000-66696000	Deferred        msacm32
PE	68c40000-68d3d000	Deferred        shlwapi
PE	6a300000-6a64e000	Deferred        oleaut32
PE	6a900000-6aa75000	Deferred        setupapi
PE	6aec0000-6aecf000	Deferred        psapi
PE	6c0c0000-6c0fb000	Deferred        imm32
PE	6d5c0000-6d733000	Deferred        dsound
PE	6e8c0000-6ec8c000	Deferred        comctl32
PE	6fb40000-6fc85000	Deferred        d3d9
PE	6fdc0000-6ff8e000	Deferred        rpcrt4
PE	70340000-703b4000	Deferred        mmdevapi
ELF	79a03000-7a800000	Deferred        i965_dri.so
ELF	7a800000-7a949000	Deferred        opengl32<elf>
  \-PE	7a840000-7a949000	\               opengl32
ELF	7ac93000-7ad1f000	Deferred        libvorbisenc.so.2
ELF	7ad1f000-7ae00000	Deferred        libgcrypt.so.20
ELF	7af12000-7af71000	Deferred        libflac.so.8
ELF	7af71000-7b000000	Deferred        libsndfile.so.1
PE	7b000000-7b274000	Deferred        kernelbase
ELF	7b274000-7b28c000	Deferred        libgpg-error.so.0
ELF	7b28c000-7b2b7000	Deferred        libvorbis.so.0
ELF	7b2b7000-7b2e3000	Deferred        liblzma.so.5
ELF	7b2e3000-7b373000	Deferred        libsystemd.so.0
ELF	7b373000-7b400000	Deferred        libpulsecommon-11.1.so
ELF	7b400000-7b671000	Deferred        kernel32<elf>
  \-PE	7b420000-7b671000	\               kernel32
ELF	7b679000-7b682000	Deferred        libogg.so.0
ELF	7b682000-7b698000	Deferred        liblz4.so.1
ELF	7b698000-7b6f3000	Deferred        libdbus-1.so.3
ELF	7b6f3000-7b74d000	Deferred        libpulse.so.0
ELF	7b77d000-7b7b0000	Deferred        winepulse<elf>
...
ELF	f7f21000-f7f49000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) C:\games\fallout2\fallout2.exe
	00000030   15
	0000002f   15
	0000002e    0
	00000009    0 <==
0000000e services.exe
	00000024    0
	0000001d    0
	0000001a    0
	00000013    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	00000017    0
	00000016    0
	00000012    0
00000018 winedevice.exe
	00000021    0
	0000001e    0
	0000001c    0
	0000001b    0
	00000019    0
0000001f explorer.exe
	0000002b    0
	0000002a    0
	00000029    0
	00000028    0
	00000020    0
00000022 winedevice.exe
	00000027    0
	00000026    0
	00000025    0
	00000023    0
System information:
    Wine build: wine-5.0.1
    Platform: i386
    Version: Windows 7
    Host system: Linux
    Host version: 4.15.0-106-generic

```

**Comment by GDRFunk** [comment]
[Magus senpai.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/4810027/Magus.senpai.zip)
Also, sorry about the clarity, English is not my native language and it's kinda difficult to explain certain things.

**Comment by FakelsHub** [comment]
Напиши в каком шаге присходит сбой.

**Comment by burner1024** [comment]
просто ход закончить

**Comment by FakelsHub** [comment]
Вроде это решается скриптово, уже не однократно встречал краши-баги в конце/в ходе боя всяких люшпенов. (на NC уже вроде какие-то баги с этим исправляли)

**Comment by FakelsHub** [comment]
> Unhandled page fault on read access to 0C153428 at address 00458646

копай в сторону `op_critter_state`

**Comment by burner1024** [comment]
@FakelsHub 
> копай в сторону op_critter_state

![Captura de pantalla de 2020-06-23 00-55-40](https://user-images.githubusercontent.com/1279852/85319797-47511880-b4ec-11ea-8468-b40366a266fd.png)

И ничего конкретного я по тем ссылкам не вижу. Если проблема известная, то наверное правильно в движке зачинить. Ну или хотя бы залогировать четко...

@GDRFunk 
1. You said you didn't use any other mods, how come there's traces of FO2tweaks in your savegames?
![Captura de pantalla de 2020-06-23 00-09-21](https://user-images.githubusercontent.com/1279852/85320234-f857b300-b4ec-11ea-8f85-bd2d656973c0.png)
2. I have retried several times now, and I cannot reproduce the crash using the **first** save. Here's Weijung killed:
![Captura de pantalla de 2020-06-23 01-02-15](https://user-images.githubusercontent.com/1279852/85320445-440a5c80-b4ed-11ea-8b2b-7aadd65bee8a.png)
  Try a few more times, see how reliable it is.
3. After that, drop everyone from the party and try a few times more.

**Comment by GDRFunk** [comment]
1.-  used FO2 tweaks when I started the game like 1 month ago, but then I switched to my main PC and just using a regular fo2 with UP
2 - 3.- Still trying, dropped Marcus and I still getting the same crash with the last fight.

**Comment by burner1024** [comment]
1. This is the information that you should provide upfront, also if you used any cheats, editors, etc.
2 and 3 - first, let's keep them separate. Second, what do you mean by the same crash in the last fight? Before it was a crash in the second fight. If it's in the last now, then it's a different one.

**Comment by GDRFunk** [comment]
It's the same error, but now in the last fight. I dropped Marcus in the Shi temple.

**Comment by FakelsHub** [comment]
И ничего конкретного > функцию critter_state в скрипте смотри

**Comment by burner1024** [comment]
@FakelsHub 
> И ничего конкретного > функцию critter_state в скрипте смотри
> Проверь скрипт в RP FixedEdition от Foxx

Каком скрипте? Ло Пана? Уже смотрел, там killap что-то менял, пробовал удалить, результата нет. В Fixed изменений немало, но конкретно строчки с critter_state те же самые.

@GDRFunk
> It's the same error, but now in the last fight.

If it's not the same fight, it's not the same.
Are you saying that you can't reproduce the crash that is described in the first message anymore?

**Comment by FakelsHub** [comment]
> Каком скрипте? Ло Пана? Уже смотрел, там killap что-то менял, пробовал удалить, результата нет. В Fixed изменений немало, но конкретно строчки с critter_state те же самые.

Ну я не знаю какие там скрипты используются, смотреть нужно то что передается в фукцию указатель критера. Просто смотреть  смысла нет.  Закоментируй функцию, как вариатн и проверяй.
По адресу ошибки на скрине в первом сообщении особо ничего не скажешь, там баг глубоко в код движка проник.

**Comment by FakelsHub** [comment]
слот8: вылет на функции tile_num где-то в скрипте лошпена.
кто писал такой багнутый скрипт?

**Comment by burner1024** [comment]
Судя по всему, он примерно такой и был всегда.

**Comment by FakelsHub** [comment]
>Судя по всему, он примерно такой и был всегда. Хотя собственно, даже если объект и не криттер, то тайл-то у него все равно должен быть, нет?

посмотрел в оригинале он почти такой-же.
да должен быть тайл, на первом скрине ошибка обращения к объекту на тайле карты.
скорее всего какой-то объект удаляется, а указатель остается старый, или вообще какой-то левый указатель берется и записывается в LVAR.
в общем логирование надо сделать, в каком именно месте берется и записывается пурга.

**Comment by burner1024** [comment]
ок буду разбираться
