### ISSUE TITLE
Non-existent animation in MCSLAG.ssl

### ISSUE THREAD

**Issue by NovaRain** [BGforgeNet/Fallout2_Unofficial_Patch#54]
This line: https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/scripts_src/modoc/mcslag.ssl#L156

There's no `ANIM_magic_hands_up` frame (AM) for any critter in the game. It's probably a reserved slot but anim was never made. Just noticed that because I was getting warning msg for missing frames when visiting Ghost Farm during the night.
I think it's better to change the line to `anim(self_obj, random(ANIM_magic_hands_ground, ANIM_magic_hands_middle), 0);` for slags "picking up" stuff  in the farm (maybe corn fall on the ground). Also because they have both AK/AL frames.

**Comment by burner1024** [comment]
Cool, added - thanks!
