### ISSUE TITLE
Thomas Moore cannot be exposed as NCR agent if the Bishops are made hostile

### ISSUE THREAD

**Issue by Player701** [BGforgeNet/Fallout2_Unofficial_Patch#66]
Hello! I'm going to report this here, even though I'm using the patch from killap.net, but I guess that one isn't updated anymore, and since the relevant scripts are the same, maybe you will be able to fix this.

**Describe the bug**
If you successfully complete the quest [Deliver Moore's briefcase to Mr. Bishop in New Reno](https://fallout.fandom.com/wiki/Deliver_Moore's_briefcase_to_Mr._Bishop_in_New_Reno) but then turn the Bishop family hostile, you will not be able to report to Joanne Lynette that Thomas Moore is an NCR agent.

**To Reproduce**
See above.

**Expected behavior**
You should be able to report Thomas Moore to Lynette as long as you've completed the delivery quest successfully, regardless of what happens afterwards. At least according to the check here:
https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/f09f1b2ccbb4d87271f556e97cd2d5e140b55f37/scripts_src/main/vclynett.ssl#L1938-L1939
It doesn't make any sense to change the variable GVAR_MOORE_ACCEPT_DELIVERY at any time when the quest has already been completed, but that's exactly what happens (see below for details). It may not be entirely logical to offer this dialogue option based on just the completion of the quest, but I guess that's outside the scope of this issue.

**Actual behavior**
You cannot report Thomas Moore to Lynette if you turn the Bishop family hostile, even if you've already completed the delivery quest successfully.

**Savegame**
[SLOT02.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/5885308/SLOT02.zip)
Check gvar GVAR_MOORE_ACCEPT_DELIVERY (321) at offset 0x7A6B, the value is 4.

There's only one place in the code where this value is set:
https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/9e7843e6ff2af11a6421c30e36ee8416580bba84/scripts_src/headers/newreno.h#L732-L734

It looks like this is a new addition judging by the comments. This particular value is not checked for anywhere else. Perhaps this assignment should be removed entirely or only be triggered when the quest hasn't been already completed. I'm not very familiar with the specifics of Fallout scripting, so you should know better what to do to make sure the quest gets properly crossed out of the pip-boy quest list at all times.

**Screenshots**
N/A

**Environment**
- UPU version: 1.02.31 from killap.net, but the issue should be applicable to the latest version from this repo as well.

**Comment by burner1024** [comment]
[ncbishop.int.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/5892001/ncbishop.int.zip)
Try this.

**Comment by Player701** [comment]
Thank you very much! I don't have a save file from before I attacked Bishops, but I will make sure to use this version of the patch (including the updated script) in my next playthrough. As I understand, this seems to be the most up-to-date version, but I found this repository entirely by chance - most of my attempts to find an unofficial patch for Fallout 2 (and I mean patch, i.e. fixes only and no new content) led me to killap.net.

**Comment by Player701** [comment]
Sorry for bumping this, but like I said, I'm rather new to Fallout modding, so I wanted to ask something.

Before starting my next playthrough, I reinstalled the game and then installed the patch from this repo on top of it (```upu_v18.exe```). Now I want to use the updated script file from this thread, but I cannot find an existing ```ncbishop.int``` file to replace with this new version. Will the updated script work correctly if I just put the new file in ```data\scripts```, or do I have to do something less trivial in order to make it work?

**Comment by burner1024** [comment]
Yes, putting it into `data/scripts` is enough.

**Comment by Player701** [comment]
Thank you very much, I will get back to you if I have any more issues with this, but I hope everything will be okay.
