### ISSUE TITLE
Game crash right after entering to NCR (Hall of Congress part)

### ISSUE THREAD

**Issue by cancer101b** [BGforgeNet/Fallout2_Unofficial_Patch#72]
### What happened
The game fail's to load a certain chunk of NCR (Hall of Congress) and crash the application.

### What you expected to happen
Game supposed to load and continue without issue.

### Possible solution

I was digging into this issue myself and I discover something. I've looked up for name of the map in [NCR town](https://fallout.fandom.com/wiki/New_California_Republic_(town)) article on a fallout wiki, I've looked for a map file for Hall of Congress, which is NCR2.map. I downloaded source code to make sure that this file exists among other maps, turns out it doesn't exist in the first place, which explains why it fails to run the application further.

I could be wrong, maybe this chunk of the map exists in other form, but nonetheless crash still happens. This might be caused by other issue, so take this in a grain of salt.

### Additional comments

The patch was installed freshly after downloading from steam; steam has the hi-res mod by default btw. and I didn't install anything besides that. I've tried to disable the hi-res mod, but the game refuses to run in the first place.

### Screenshot

I can only provide a video in this case. It's hard to show only with a screenshot.
https://user-images.githubusercontent.com/80636801/111076576-1cc94480-84ed-11eb-97bb-720c0e8ebf70.mp4

### Savegame

In the case where you wanna debug what's going on during loading.
[SLOT200.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/6136992/SLOT200.zip)

**Comment by burner1024** [comment]
Try with [debug.log](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/crash.md), attach it as well.

**Comment by cancer101b** [comment]
This is my debug log. I've done pretty much the same steps as in the clip. 

From what I can see "External variable lenny_obj does not exist" cause a crash in 232 line.

[debug.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/6137528/debug.zip)

**Comment by burner1024** [comment]
[I can't reproduce](https://www.loom.com/share/5e415c55f1b144c1a075b71476efa17b).
Debug log looks fine. Please attach `ddraw.dll` and `ddraw.ini`.
Also, I'd try a fresh installation (separate directory), just in case.

**Comment by cancer101b** [comment]
I've done clear installation, but crash still happens.

I've done debugging one again just in case; I'm sending log with `ddraw.dll` and `ddraw.ini`
[debug&ddraw.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/6139863/debug.ddraw.zip)

**Comment by cancer101b** [comment]
I've discovered something interesting. Out of curiosity, I've tried boot fallout on the virtual machine, turns out it's working there, but not in my main system. And I'm wondering why, did fallout have some kind of files stored in AppData or something similar that could be corrupted? Playing on virtual sound like a solution, but to be honest I would like to truly fix it. Any idea why is this a case? I need to say It's a weird state at this point.

**Comment by burner1024** [comment]
Settings look fine too.
It is weird indeed. How'd you get Fallout into VM? Fresh installation or copy from host?

**Comment by cancer101b** [comment]
> How'd you get Fallout into VM? Fresh installation or copy from host?

Tried both of them, yesterday firstly I've tried with a fresh installation, and later in a day in the evening, I've copied my main files. Both are working just fine.

> Try different video settings: DX9/DDraw, windowed/fullscreen.

I've been combining with these settings back on Friday when this started to occur; some DX settings don't even let me boot game in the first place.

Right now I'm trying to play alternately on VM and in the host, especially when I'm heading to Hall of Congress in my case. It works for sure, but it's not how it should be solved in the long run.

What I mean by that is this weird anomaly probably happens even without the patch and for everyone in different places. Before my current try with the game, I've started playing without the patch, when I was heading to the Den on the west side and my game was also crashing every time when I was trying to enter the area. In other PC's this could be in e. g. Vault City, New Reno, Broken Hill's you name it. I do a quick search for some other locations and I came to realize that different people in different locations are struggling with crashes. My way of fixing the issue might be too complicated for some folks or impossible for even running a second machine at the same time.

Combining this and the fact that on fresh windows, the game works just fine I came to realize, that after time game could create files in the system that uses to boot with application globally, no matter where the game directory will be. Those files overtime could be in some way broken, and as a result crash in certain places. This might be using personal data dir, AppData files, or even register; I could only speculate.

I gave an idea, but I didn't expect you to look into that deeper and I shouldn't. It's your software and your rules; If you want to close the case already, feel free to do it; for me, the solution has been found. Thank you for your time!

**Comment by burner1024** [comment]
>  I do a quick search for some other locations and I came to realize that different people in different locations are struggling with crashes.

F2 is crash-ridden in general. And of course, each crash happens in *some* location. So this result in not rreally surprising.
A lot was fixed over the years, but a lot still remains.

If you find any further information, feel free to share, but for now there's not much to do.
