### ISSUE TITLE
AI.txt

### ISSUE THREAD

**Issue by FakelsHub** [BGforgeNet/Fallout2_Unofficial_Patch#73]
https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/5210d10feb546d27e4f32836ed096c4cb19bf3b3/data/data/ai.txt#L1565

У геско по хорошему это должно быть установлено в `clear` (выключено).

**НЕ актуально.**

**Comment by burner1024** [comment]
Да почему удалять-то, наоборот написал бы почему неактуально, чтобы всем было понятно.
А вообще ты же и сам можешь править, у тебя доступ есть.

**Comment by FakelsHub** [comment]
Я не могу удалять,
Ладно тогда надо привести аi.txt в порядок опцию chem_primary_desire для  некоторых партийцев установить в -1 (или удалить опцию) в соотвествии с опцией

**Comment by burner1024** [comment]
Я и сам не вижу кнопки удалить, может вообще нельзя.
Я имею ввиду, к репозиторию доступ у тебя есть.

**Comment by burner1024** [comment]
Так что будем чинить?

**Comment by FakelsHub** [comment]
`chem_primary_desire` у партийцев людей установить в -1, там сейчас везде 81 (это вроде мясо) это значение должно быть установлено только у всяких собак/животин.

**Comment by burner1024** [comment]
Так тогда не только у партийцев, но и у всех, кроме животных?

**Comment by FakelsHub** [comment]
Не знаю насчет не партийцев.
Если включить исправление AIDrugUsePerfFix=2 то такой нпс будет использовать только те химикаты которые перечислены в списке. (так было задумано изначально, но все как обычно разработчиками похерено было).

**Comment by FakelsHub** [comment]
Если ты удалил не упартийцев то наверное ты этим нарушил их поведение.
Удаление позволит им поднимать с карты всякую дрянь типа яблок. :-)

**Comment by burner1024** [comment]
так удаление и -1 это не одно и то же?

**Comment by FakelsHub** [comment]
одно и тоже, но лучше использовать -1.

Вот ты у [Khan] удалил chem_primary_desire=87
Зачем?

**Comment by burner1024** [comment]
87 я не заметил, думал там 81 как везде.

>  с исправлением: не поднимает и не употребляет ничего кроме Баффoута. (стимпаки не учитываются)

Т.е. употребляет баффоут и стимпаки, так?

Мне кажется, люди вообще ничего поднимать не должны в бою. Я ему в голову стреляю, а он игнорирует и за таблеткой бежит через полэкрана?

**Comment by FakelsHub** [comment]
> Т.е. употребляет баффоут и стимпаки, так?

да.

**Comment by FakelsHub** [comment]
> 87 я не заметил, думал там 81 как везде.

там еще были значения не 81.

**Comment by burner1024** [comment]
Ну в общем сами сделали фикс, сами и включайте. Я не знаю, как его использовать правильно.

**Comment by FakelsHub** [comment]
да просто требовалось поставить для партийцев -1.
