### ISSUE TITLE
Misaligned door in Modoc

### ISSUE THREAD

**Issue by Iniquitatis** [BGforgeNet/Fallout2_Unofficial_Patch#76]
### What happened
After exploding the infamous outhouse, the entrance door in the Rose's Bed and Breakfast became shifted.

### What you expected to happen
The same as it was before the explosion.

### Screenshot
![scr00000_e](https://user-images.githubusercontent.com/5585984/116000336-6c288780-a5f8-11eb-96bd-81c9a72621af.png)

### Savegame
[SLOT02.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/6372348/SLOT02.zip)

**Comment by burner1024** [comment]
Hm, as far as I can see there's not supposed to a door at all after the explosion. Not sure how you got it.
Can you try and replay the part? From before the explosion, and preferably before entering Modoc inn map.

**Comment by burner1024** [comment]
Can't reproduce, closed until there's more info.
