### ISSUE TITLE
'Err...' message in dialogs

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [BGforgeNet/Fallout2_Unofficial_Patch#82]
### What happened
I see 'Err...' message in dialogs sometimes. I play with IN=1 and it happens when I increase IN with mentats, take some quest, then return back to quest owner after IN decreased to 1 again. 

### What you expected to happen
Not sure is it bug or not. Does 'Err...' means 'Error' ?

### Screenshot
One of examples: 
![scr00000](https://user-images.githubusercontent.com/19704782/149003616-c45ab4ea-e59f-4df7-bc25-37ef804e173a.png)

### Savegame
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/7849156/SLOT04.zip)

There is no 'Err...' message in https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/data/text/english/dialog/vcmainwk.msg

**Comment by burner1024** [comment]
It does. There's no dialog branch for stupid character in this scenario. [The only](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/c9a973c99927be03e3f8a85a777cc0e274c49b46/scripts_src/valtcity/vcmainwk.ssl#L609) available option requires INT 4.

**Comment by dzmitry-rudnouski** [comment]
Should I report other similar cases?

**Comment by burner1024** [comment]
I guess no. It's just an unimplemented use case.
What would you do about it? Write new dialog? That doesn't really fall into patch scope.
And I don't see the point of running stupid if you're just going to mentat your way through stuff.
So, I don't think it's something actionable.

**Comment by dzmitry-rudnouski** [comment]
Looks like not a bug at all. 'Err' is normal english word, I see it in other dialogs: https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/data/text/english/dialog/fcdragon.msg#L83
Closing.
