### ISSUE TITLE
Broken barter

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [BGforgeNet/Fallout2_Unofficial_Patch#83]
### What happened
Talk to woman. Select 1-1-1-1 in dialogs. Empty barter window appears. TALK button doesn't work.

### What you expected to happen
Barter is not broken.

### Screenshot
![scr00000](https://user-images.githubusercontent.com/19704782/150024478-cd2ed5a0-fd5e-416f-8060-b605fd587879.jpg)

### Savegame
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/7892579/SLOT04.zip)
[debug.log](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/7892593/debug.log)

**Comment by burner1024** [comment]
[hcliz.int.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/7896601/hcliz.int.zip)
Extract this into `data/scripts`, first option shouldn't appear anymore.

**Comment by dzmitry-rudnouski** [comment]
Verified, thank you.
