### ISSUE TITLE
Broken barter #2

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [BGforgeNet/Fallout2_Unofficial_Patch#84]
### What happened
Talk to man, select 1 in dialog. Barter is broken.

### What you expected to happen
Barter is ok.

### Screenshot
![scr00001](https://user-images.githubusercontent.com/19704782/150407145-522f4cdd-cfc9-42c5-acaa-9b151c70b7d7.png)

### Savegame
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/7907927/SLOT04.zip)

**Comment by burner1024** [comment]
Yeah, you're playing with an unusual PC, so you'll possibly run into a couple of these.

**Comment by burner1024** [comment]
Hotfix [scmikey.int.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/7911242/scmikey.int.zip)

Can drop more of the same into this issue.
