### ISSUE TITLE
dude_iq_talk is used in hcliz.ssl only

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [BGforgeNet/Fallout2_Unofficial_Patch#86]
### What happened
You introduced two new variables: dude_iq_talk and dude_is_stupid_talk in [91a162ee6e68173ad6e8c9632c21d682c326101e](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/commit/91a162ee6e68173ad6e8c9632c21d682c326101e).
But they are used in scripts_src/brokhill/hcliz.ssl only.

### What you expected to happen
I suppose we need to replace dude_iq and dude_is_stupid with dude_iq_talk and dude_is_stupid_talk in all scripts, no?

**Comment by burner1024** [comment]
No, because that specifically determines PC eligibility for response options, and there's a lot of other IQ checks that are not about responses, and there's also non-dialogue ones.
But there could be some cases where it should be replaced. If you want to give a try, be my guest.

**Comment by dzmitry-rudnouski** [comment]
Let's try. Here is the 1st one: #87
