### ISSUE TITLE
Black screen special encounter

### ISSUE THREAD

**Issue by MaybeZak** [BGforgeNet/Fallout2_Unofficial_Patch#90]
### What happened
Got black screen when I got a special encounter then the game crashed
### What you expected to happen
For it to be a normal special encounter
### Screenshot
![Screenshot (81)](https://user-images.githubusercontent.com/99081647/152645082-edb6527e-939e-4085-8284-2b8913708a2e.png)

### Savegame
Tried uploading but Github doesn't support the file type so just sending random gta sa screenshot because I need to upload another file to be able to submit this

![Screenshot (54)](https://user-images.githubusercontent.com/99081647/152645169-b29e439c-3948-4e72-aca0-4033071fb4d3.png)

**Comment by NovaRain** [comment]
Disable `FadeBackgroundMusic` in ddraw.ini, or update sfall (ddraw.dll) to [4.3.3](https://github.com/phobos2077/sfall/releases/tag/v4.3.3).

**Comment by Felipefpl** [comment]
> Tried uploading but Github doesn't support the file type so just sending random gta sa screenshot because I need to upload another file to be able to submit this

This means you dont have a tool like www.7-zip.org to create zip files to upload your saves?

**Comment by MaybeZak** [comment]
Do I need a fresh save file to download the new sfall release?

**Comment by MaybeZak** [comment]
> > Tried uploading but Github doesn't support the file type so just sending random gta sa screenshot because I need to upload another file to be able to submit this
> 
> This means you dont have a tool like [www.7-zip.org](http://www.7-zip.org) to create zip files to upload your saves?

Oh yeah my fault I should have archived it with 7zip, sorry

**Comment by MaybeZak** [comment]
> Disable `FadeBackgroundMusic` in ddraw.ini, or update sfall (ddraw.dll) to [4.3.3](https://github.com/phobos2077/sfall/releases/tag/v4.3.3).

Do I need a fresh save file to download the new sfall release?

**Comment by NovaRain** [comment]
> > Disable `FadeBackgroundMusic` in ddraw.ini, or update sfall (ddraw.dll) to [4.3.3](https://github.com/phobos2077/sfall/releases/tag/v4.3.3).
> 
> Do I need a fresh save file to download the new sfall release?

No. You can update the sfall and continue your save games. Just remember do not overwrite your existing ddraw.ini with the one from the release.

**Comment by burner1024** [comment]
@maybezak  Did update work for you?

**Comment by burner1024** [comment]
not enough info
