### ISSUE TITLE
Options are not displayed for Tubby

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [BGforgeNet/Fallout2_Unofficial_Patch#91]
### What happened
Please help me understand why 2 options are not displayed:
https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/scripts_src/den/dctubby.ssl#L326,L327
IQ=3 (or 4 with smooth_talker), it's greater than -003.

### Savegame
[SLOT01.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/8009902/SLOT01.zip)

**Comment by Lexx2k** [comment]
-003 is just a different way of turning this into a dumb dialog option.

**Comment by dzmitry-rudnouski** [comment]
Found the answer.
NOption is macros for giQ_Option. And here is iq_test parameter description.
Int: When Int is positive (1 to 10), then this means "player has Int or equal", so 4 means that the player requires 4 int or more to see this answer option. When Int is negative (-1 to -9), this means that the player needs ot have less or equal. So -3 means "player has 3 of Int or less"
