### ISSUE TITLE
Set up game resolution is annoying and unpredictable

### ISSUE THREAD

**Issue by WebTiger89** [BGforgeNet/Fallout2_Unofficial_Patch#93]
It is a pain to set up the resolution and also confusing. If I understand the ddraw.ini comments right there are currently 2 high-res modes available. I guess one of them is deprecated. Settings like:

```
HiResMode=0

Mode=4

GraphicsWidth=0
GraphicsHeight=0
```
or
```
GRAPHICS_MODE=2

SCALE_2X=0

SCR_WIDTH=1024
SCR_HEIGHT=768

WINDOWED=0
```
doesn't make it better and add more confusion on top. Can you remove the older high-res patch and other old settings from 20th century that no one needs anymore? Additionally in window mode the resolution is always the same as Windows settings, in my case 1920x1080, no matter what is defined in ini files. And you cannot play the game in such a huge resoluton. It's too small. I claim the best solution for everyone, despite of the size of the monitor is 1024x768. In this resolution there are black bars on the left and right...the game is centered. You should focus on support this resolution properly because it's the only real playable resolution. I would like to see 1024x768 in stretch mode.

**Comment by burner1024** [comment]
There are multiple graphics options, and it can get confusing, that's true.
The "older" hi-res patch is not from the 20th century. It's not going to be removed any time soon.
The unofficial patch is not about resolution, it's about fixing game bugs. Any issues about resolution, you can direct to hi-res (old) and sfall (new) developers.
