### ISSUE TITLE
Some german msg files are messed up

### ISSUE THREAD

**Issue by WebTiger89** [BGforgeNet/Fallout2_Unofficial_Patch#94]
If you in a party, e.g. Sulik and you tell him to wait and later want to collect him again the message entry is missleading. In german:

{2810}{}{Dann lass uns mal Tyler kalt stellen.}

https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/28332ebe1035df1436cd4ba6aeaf4bbbaaaddd56/data/text/german/dialog/dcvic.msg

This text snippet indicates that the quest in "The Den" to kill Tyler with Lara's gang is always persistent.
The english pendants just have "Let's go.".

Just of curiosity. Where can I find the link to {2810}. Where can I find the behavior to this message entry?

**Comment by burner1024** [comment]
The translation is incomplete, as [described](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/translations.md).
You can browse and fix translations [here](https://tra.bgforge.net/translate/fallout/up/de/?checksum=&offset=&q=Dann+lass+uns+mal+Tyler+kalt+stellen&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=).

**Comment by WebTiger89** [comment]
@burner1024 What about this:
Just of curiosity. Where can I find the link to {2810}. Where can I find the behavior to this message entry?

**Comment by burner1024** [comment]
The link is in my previous response.

**Comment by WebTiger89** [comment]
@burner1024 No I'm looking for the scripting/modding part. Where is the game logic that is triggered when specific messages are selected. Where are the conditions defined to unlock message options etc.

**Comment by WebTiger89** [comment]
@burner1024 ok thanks, can you tell me where the corresponding script file to this is:

> # 1014 Waiting
{2800}{}{Hey, Boss. You want me to join up with you now?}
{2801}{}{Hey, Boss. I don't mind waiting for you. I'm a real patient man.}
{2802}{}{We joining up again, Boss? I'll try harder.}

https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/data/text/english/dialog/dcvic.msg

**Comment by burner1024** [comment]
It is [dcvic.ssl](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/f2337c932f8846df2f029beff66db4e5513a8211/scripts_src/den/dcvic.ssl#L767).

**Comment by WebTiger89** [comment]
@burner1024  Yeah I found this line too, but I can't find 2810-2812. Any ideas?

**Comment by burner1024** [comment]
No.
