### ISSUE TITLE
Infinite EXP bug with Merk in NCR

### ISSUE THREAD

**Issue by lanhdongls** [BGforgeNet/Fallout2_Unofficial_Patch#98]
Accepted Merk's quest to kill Hubologist.
Killed the Hubologist.
Talk to Merk to receive EXP reward.
Follow dialogue in screenshot to get infinite EXP.
### Screenshot
![scr00004](https://user-images.githubusercontent.com/109055874/178187745-af5e1eab-76d5-4b53-84a0-b3189b17f56e.jpeg)
![scr00005](https://user-images.githubusercontent.com/109055874/178187869-51c021db-3922-40e7-8473-b9275a430135.jpeg)
![scr00006](https://user-images.githubusercontent.com/109055874/178187914-7b136491-228a-4d9d-8699-30b8a9c1010d.jpeg)
![scr00007](https://user-images.githubusercontent.com/109055874/178188018-c8a41243-29c9-4179-9b67-988c6d1557bb.jpeg)

### Savegame
[SLOT09.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/9080885/SLOT09.zip)

**Comment by burner1024** [comment]
[merk.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/9081428/merk.zip)
unzip into `data`, should fix it
